### ISSUE TITLE
Database routines

### ISSUE THREAD

**Issue by Virtakuono** [StochasticNumerics/mimclib#22]
This is not a very well-formed request yet, but I think a few helper scripts to manipulate the database should be in place for us idiots who aren't wizards and who don't know exactly how the things look at the mysql backend even if we knew the syntax.

As of now, I can think of two functions that I have needed:
1. Remove everything with a given db_tag
2. I have done an alteration to a code but forgot to update the db_tag, so I need to remove N latest runs with a given db_tag.

This is by no means urgent,  I'll leave the thread open just to collect more ideas on what might be useful to implement.

**Comment by haji-ali** [comment]
I disagree a little, but only a little. The idea of using a database is to be able to use the standard mysql engine to do all sort of unpredictable data management.
Imagine if we were using files instead of a database (I am planning to add a module like that eventually), you wouldn't expect a file management functionality from the module. That is something that is provided by the operating system.

With that being said, I don't see a harm of adding a few very common functionalities.
The database scheme will also be documented eventually so that those that know SQL can do their own data management.

**Comment by Virtakuono** [comment]
Yup. Anything we do should not be at the cost of the advanced users being able to do their high-level mysql-witchcraft.

For the _unpredictable_ data management that is needed, but I'd assume 80 per cent of the things people do are not unpredictable, and for those everyday predictable things a few helper templates might be useful.

**Comment by haji-ali** [comment]
OK. Done
Now you can do something like

> db = mimclib.db.MIMCDatabase()
> db.deleteRuns(db.getRunsIDs(tag="MyTag", from_date=datatime.date(1999,1,1), to_date=datatime.date(2016,1,1)))

All arguments to getRunsIDs are optional.

**Comment by Virtakuono** [comment]
Well that was fast! Thanks.

**Comment by litvinen** [comment]
Given db_tag, with which shell-command I can extract the corresponding log file from mysql database?

**Comment by haji-ali** [comment]
You can't

**Comment by litvinen** [comment]
Is there any other useful info in the log file? or info which is contained in 12 plots is completely enough?
